// <auto-generated />
using System;
using GLMS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GLMS.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260613134232_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GLMS.API.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("ContactDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            ContactDetails = "contact@techmove.com",
                            Name = "TechMove Logistics",
                            Region = "North America"
                        },
                        new
                        {
                            ClientId = 2,
                            ContactDetails = "info@globalshipping.com",
                            Name = "Global Shipping Inc",
                            Region = "Europe"
                        },
                        new
                        {
                            ClientId = 3,
                            ContactDetails = "sales@asiafreight.com",
                            Name = "Asia Freight Solutions",
                            Region = "Asia Pacific"
                        });
                });

            modelBuilder.Entity("GLMS.API.Models.Contract", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ServiceLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignedAgreementFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignedAgreementPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContractId");

                    b.HasIndex("ClientId");

                    b.ToTable("Contracts");

                    b.HasData(
                        new
                        {
                            ContractId = 1,
                            ClientId = 1,
                            EndDate = new DateTime(2026, 12, 13, 15, 42, 31, 880, DateTimeKind.Local).AddTicks(3120),
                            ServiceLevel = "Premium",
                            StartDate = new DateTime(2025, 12, 13, 15, 42, 31, 880, DateTimeKind.Local).AddTicks(3089),
                            Status = "Active"
                        },
                        new
                        {
                            ContractId = 2,
                            ClientId = 1,
                            EndDate = new DateTime(2026, 5, 13, 15, 42, 31, 880, DateTimeKind.Local).AddTicks(3125),
                            ServiceLevel = "Standard",
                            StartDate = new DateTime(2025, 6, 13, 15, 42, 31, 880, DateTimeKind.Local).AddTicks(3124),
                            Status = "Expired"
                        },
                        new
                        {
                            ContractId = 3,
                            ClientId = 2,
                            EndDate = new DateTime(2026, 9, 13, 15, 42, 31, 880, DateTimeKind.Local).AddTicks(3128),
                            ServiceLevel = "Express",
                            StartDate = new DateTime(2026, 3, 13, 15, 42, 31, 880, DateTimeKind.Local).AddTicks(3127),
                            Status = "Active"
                        },
                        new
                        {
                            ContractId = 4,
                            ClientId = 3,
                            EndDate = new DateTime(2026, 11, 13, 15, 42, 31, 880, DateTimeKind.Local).AddTicks(3131),
                            ServiceLevel = "Standard",
                            StartDate = new DateTime(2026, 5, 13, 15, 42, 31, 880, DateTimeKind.Local).AddTicks(3130),
                            Status = "Draft"
                        });
                });

            modelBuilder.Entity("GLMS.API.Models.ServiceRequest", b =>
                {
                    b.Property<int>("ServiceRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceRequestId"));

                    b.Property<decimal>("AmountUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountZAR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ExchangeRateUsed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServiceRequestId");

                    b.HasIndex("ContractId");

                    b.ToTable("ServiceRequests");
                });

            modelBuilder.Entity("GLMS.API.Models.Contract", b =>
                {
                    b.HasOne("GLMS.API.Models.Client", "Client")
                        .WithMany("Contracts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("GLMS.API.Models.ServiceRequest", b =>
                {
                    b.HasOne("GLMS.API.Models.Contract", "Contract")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("GLMS.API.Models.Client", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("GLMS.API.Models.Contract", b =>
                {
                    b.Navigation("ServiceRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
